\set ON_ERROR_STOP on

CREATE TABLE public.accqua_class_status_fixture (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status text NOT NULL
);

INSERT INTO public.accqua_class_status_fixture (status) VALUES ('reservado');

-- Reproduz o padrão que causa a ambiguidade no banco real: a função possui
-- um campo de retorno chamado status e também consulta uma coluna status.
-- Compilamos inicialmente preferindo a variável apenas para criar o fixture;
-- a migration 1.4.6 deve recompilar a função com use_column.
SET plpgsql.variable_conflict = 'use_variable';

CREATE OR REPLACE FUNCTION public.reserve_accqua_class()
RETURNS TABLE(status text)
LANGUAGE plpgsql
AS $fixture$
BEGIN
  RETURN QUERY
  SELECT status
  FROM public.accqua_class_status_fixture;
END
$fixture$;

RESET plpgsql.variable_conflict;
