import { useEffect, useState, type FormEvent } from "react";
import StaffShell from "../../components/StaffShell";
import { Card } from "../../components/AppShell";
import Icon from "../../components/Icon";
import Modal from "../../components/Modal";
import { InputField, SelectField, TextareaField } from "../../components/Field";
import { supabase } from "../../lib/supabase";

interface Row{id:string;name:string;category:string;description:string|null;gympass_tier:string|null;active:boolean;schedule_id:string;day_of_week:number;starts_at:string;ends_at:string|null;instructor:string|null;location:string|null;capacity:number|null;}
const days=["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"];
const blank:any={name:"",category:"Coletiva",description:"",gympass_tier:"",active:true,day_of_week:1,starts_at:"18:00",ends_at:"19:00",instructor:"",location:"",capacity:20};
export default function ClassesManager(){
 const [rows,setRows]=useState<Row[]>([]);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Row|null>(null);const [form,setForm]=useState(blank);
 async function load(){const {data}=await supabase.from("class_schedule_view").select("*").order("day_of_week").order("starts_at");setRows((data||[]) as Row[]);}useEffect(()=>{void load();},[]);
 function create(){setEditing(null);setForm(blank);setOpen(true);}function edit(row:Row){setEditing(row);setForm({...row});setOpen(true);}
 async function save(e:FormEvent){e.preventDefault();if(editing){await supabase.from("classes").update({name:form.name,category:form.category,description:form.description,gympass_tier:form.gympass_tier,active:form.active}).eq("id",editing.id);await supabase.from("class_schedules").update({day_of_week:Number(form.day_of_week),starts_at:form.starts_at,ends_at:form.ends_at||null,instructor:form.instructor,location:form.location,capacity:Number(form.capacity)||null}).eq("id",editing.schedule_id);}else{const {data}=await supabase.from("classes").insert({name:form.name,category:form.category,description:form.description,gympass_tier:form.gympass_tier,active:form.active}).select("id").single();if(data)await supabase.from("class_schedules").insert({class_id:data.id,day_of_week:Number(form.day_of_week),starts_at:form.starts_at,ends_at:form.ends_at||null,instructor:form.instructor,location:form.location,capacity:Number(form.capacity)||null});}setOpen(false);await load();}
 async function remove(row:Row){if(confirm("Excluir esta aula e seus horários?")){await supabase.from("classes").delete().eq("id",row.id);await load();}}
 return <StaffShell title="Gerenciar aulas" subtitle="Atualize aulas coletivas, horários, locais e planos aceitos." right={<button className="button primary small" onClick={create}><Icon name="plus"/> Aula</button>}>
  <div className="class-manager-list">{rows.map(row=><Card key={row.schedule_id}><span className="class-icon"><Icon name={row.category.toLowerCase().includes("nata")?"swim":"run"}/></span><div><strong>{row.name}</strong><small>{days[row.day_of_week]} · {row.starts_at.slice(0,5)}{row.ends_at?`–${row.ends_at.slice(0,5)}`:""} · {row.location||"Academia"}</small><span>{row.gympass_tier?`Wellhub ${row.gympass_tier}`:"Sem plano informado"}</span></div><div><button className="icon-button" onClick={()=>edit(row)}><Icon name="edit"/></button><button className="icon-button danger" onClick={()=>void remove(row)}><Icon name="trash"/></button></div></Card>)}</div>
  <Modal open={open} title={editing?"Editar aula":"Nova aula"} onClose={()=>setOpen(false)} wide><form className="form-grid" onSubmit={save}><InputField label="Nome" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><SelectField label="Categoria" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Coletiva</option><option>Natação</option><option>Hidroginástica</option><option>Funcional</option><option>Ritmos</option></SelectField><SelectField label="Dia" value={form.day_of_week} onChange={e=>setForm({...form,day_of_week:Number(e.target.value)})}>{days.map((d,i)=><option value={i} key={d}>{d}</option>)}</SelectField><InputField label="Início" type="time" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/><InputField label="Fim" type="time" value={form.ends_at||""} onChange={e=>setForm({...form,ends_at:e.target.value})}/><InputField label="Local" value={form.location||""} onChange={e=>setForm({...form,location:e.target.value})}/><InputField label="Professor" value={form.instructor||""} onChange={e=>setForm({...form,instructor:e.target.value})}/><InputField label="Plano Wellhub/Gympass" value={form.gympass_tier||""} onChange={e=>setForm({...form,gympass_tier:e.target.value})}/><InputField label="Capacidade" type="number" value={form.capacity||""} onChange={e=>setForm({...form,capacity:Number(e.target.value)})}/><label className="toggle-row"><span><strong>Aula ativa</strong></span><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><i/></label><TextareaField label="Descrição" value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})}/><button className="button primary span-2">Salvar aula</button></form></Modal>
 </StaffShell>;
}
