import { useEffect, useMemo, useState, type FormEvent } from "react";
import StaffShell from "../../components/StaffShell";
import { Card } from "../../components/AppShell";
import Icon from "../../components/Icon";
import Modal from "../../components/Modal";
import { InputField, SelectField, TextareaField } from "../../components/Field";
import { useAuth } from "../../context/AuthContext";
import { firstName } from "../../lib/format";
import { supabase } from "../../lib/supabase";
import type { Profile } from "../../lib/types";

export default function StudentsManager(){
 const {profile,canApproveStudents}=useAuth();const [students,setStudents]=useState<Profile[]>([]);const [professors,setProfessors]=useState<Profile[]>([]);const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");const [selected,setSelected]=useState<Profile|null>(null);const [form,setForm]=useState<any>(null);const [teacherId,setTeacherId]=useState("");const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
 async function load(){setLoading(true);const [studentResult,teacherResult]=await Promise.all([supabase.from("profiles").select("*").eq("role","student").order("full_name"),supabase.from("profiles").select("*").eq("role","professor").eq("status","active").order("full_name")]);setStudents((studentResult.data||[]) as Profile[]);setProfessors((teacherResult.data||[]) as Profile[]);setLoading(false);}
 useEffect(()=>{void load();},[]);
 const visible=useMemo(()=>students.filter(s=>(filter==="all"||s.status===filter)&&`${s.full_name} ${s.email} ${s.cpf}`.toLowerCase().includes(query.toLowerCase())),[students,filter,query]);
 function open(student:Profile){setSelected(student);setForm({...student,weight_kg:student.weight_kg||"",height_cm:student.height_cm||""});setMessage("");}
 async function save(e:FormEvent){e.preventDefault();if(!selected)return;const payload={full_name:form.full_name,phone:form.phone,emergency_phone:form.emergency_phone,objective:form.objective,weight_kg:form.weight_kg?Number(form.weight_kg):null,height_cm:form.height_cm?Number(form.height_cm):null,status:canApproveStudents?form.status:selected.status};const {error}=await supabase.from("profiles").update(payload).eq("id",selected.id);if(error){setMessage(error.message);return;}if(teacherId&&canApproveStudents){await supabase.from("teacher_student_links").upsert({professor_id:teacherId,student_id:selected.id,active:true,linked_by:profile?.id},{onConflict:"professor_id,student_id"});}setMessage("Aluno atualizado.");await load();}
 async function quickStatus(student:Profile,status:string){const {error}=await supabase.rpc("set_student_status",{p_student_id:student.id,p_status:status});if(!error)await load();}
 return <StaffShell title="Alunos" subtitle="Pesquise, libere e acompanhe os alunos permitidos para sua conta." right={<button className="icon-button" onClick={()=>void load()}><Icon name="refresh"/></button>}>
  <div className="staff-toolbar"><label className="search-box"><Icon name="search"/><input placeholder="Nome, e-mail ou CPF" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="filter-chips">{[["all","Todos"],["pending","Pendentes"],["active","Ativos"],["inactive","Inativos"]].map(([value,label])=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{label}</button>)}</div></div>
  {loading?<div className="skeleton hero"/>:<div className="student-table">{visible.map(student=><Card key={student.id} className="student-row"><div className="student-avatar">{student.avatar_url?<img src={student.avatar_url}/>:firstName(student.full_name)[0]}</div><div><strong>{student.full_name}</strong><small>{student.email}</small><span className={`status-pill ${student.status}`}>{student.status}</span></div><div className="student-actions">{canApproveStudents&&student.status==="pending"&&<button className="button small primary" onClick={()=>void quickStatus(student,"active")}>Liberar</button>}<button className="icon-button" onClick={()=>open(student)}><Icon name="edit"/></button></div></Card>)}</div>}
  <Modal open={Boolean(selected&&form)} title={selected?`Editar ${firstName(selected.full_name)}`:"Editar aluno"} onClose={()=>{setSelected(null);setForm(null)}} wide>{form&&<form className="form-grid" onSubmit={save}><InputField label="Nome" value={form.full_name||""} onChange={e=>setForm({...form,full_name:e.target.value})}/><InputField label="E-mail" value={form.email||""} disabled/><InputField label="CPF" value={form.cpf||""} disabled/><InputField label="Telefone" value={form.phone||""} onChange={e=>setForm({...form,phone:e.target.value})}/><InputField label="Contato de emergência" value={form.emergency_phone||""} onChange={e=>setForm({...form,emergency_phone:e.target.value})}/><InputField label="Peso (kg)" type="number" value={form.weight_kg||""} onChange={e=>setForm({...form,weight_kg:e.target.value})}/><InputField label="Altura (cm)" type="number" value={form.height_cm||""} onChange={e=>setForm({...form,height_cm:e.target.value})}/>{canApproveStudents&&<SelectField label="Status" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="pending">Pendente</option><option value="active">Ativo</option><option value="inactive">Inativo</option><option value="blocked">Bloqueado</option></SelectField>}<TextareaField label="Objetivo" value={form.objective||""} onChange={e=>setForm({...form,objective:e.target.value})}/>{canApproveStudents&&<SelectField label="Vincular professor" value={teacherId} onChange={e=>setTeacherId(e.target.value)}><option value="">Não alterar</option>{professors.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</SelectField>}{message&&<div className="form-message success span-2">{message}</div>}<button className="button primary span-2">Salvar alterações</button></form>}</Modal>
 </StaffShell>;
}
