import { useEffect, useMemo, useState, type FormEvent } from "react";
import StaffShell from "../../components/StaffShell";
import { Card } from "../../components/AppShell";
import EmptyState from "../../components/EmptyState";
import Icon from "../../components/Icon";
import Modal from "../../components/Modal";
import { InputField, TextareaField } from "../../components/Field";
import { useAuth } from "../../context/AuthContext";
import { supabase } from "../../lib/supabase";
import type { ExerciseLibraryItem, Profile, WorkoutExercise, WorkoutPlan } from "../../lib/types";

const blankPlan={name:"Treino A",focus:"",review_at:"",notes:""};
const blankExercise={name:"",muscle_group:"",equipment:"",media_url:"",media_type:"gif",default_sets:3,default_reps_min:8,default_reps_max:12,default_rest_seconds:60,notes:"",visibility:"private"};

export default function WorkoutsManager(){
 const {profile}=useAuth();const [students,setStudents]=useState<Profile[]>([]);const [studentId,setStudentId]=useState("");const [plans,setPlans]=useState<WorkoutPlan[]>([]);const [plan,setPlan]=useState<WorkoutPlan|null>(null);const [items,setItems]=useState<WorkoutExercise[]>([]);const [library,setLibrary]=useState<ExerciseLibraryItem[]>([]);const [search,setSearch]=useState("");const [planOpen,setPlanOpen]=useState(false);const [exerciseOpen,setExerciseOpen]=useState(false);const [planForm,setPlanForm]=useState(blankPlan);const [exerciseForm,setExerciseForm]=useState<any>(blankExercise);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
 async function loadStudents(){const {data}=await supabase.from("profiles").select("*").eq("role","student").eq("status","active").order("full_name");const rows=(data||[]) as Profile[];setStudents(rows);if(!studentId&&rows[0])setStudentId(rows[0].id);setLoading(false);}
 async function loadLibrary(){const {data}=await supabase.from("exercise_library").select("*").order("name");setLibrary((data||[]) as ExerciseLibraryItem[]);}
 async function loadPlans(id=studentId){if(!id){setPlans([]);setPlan(null);setItems([]);return;}const {data}=await supabase.from("workout_plans").select("*").eq("student_id",id).order("version",{ascending:false});const rows=(data||[]) as WorkoutPlan[];setPlans(rows);const current=rows.find(x=>x.is_active)||rows[0]||null;setPlan(current);if(current)await loadItems(current.id);else setItems([]);}
 async function loadItems(planId:string){const {data}=await supabase.from("workout_exercises").select("*").eq("plan_id",planId).order("position");setItems((data||[]) as WorkoutExercise[]);}
 useEffect(()=>{void Promise.all([loadStudents(),loadLibrary()]);},[]);
 useEffect(()=>{if(studentId)void loadPlans(studentId);},[studentId]);
 const suggestions=useMemo(()=>library.filter(x=>`${x.name} ${x.muscle_group} ${x.equipment}`.toLowerCase().includes(search.toLowerCase())).slice(0,20),[library,search]);
 async function createPlan(e:FormEvent){e.preventDefault();if(!studentId)return;const {data,error}=await supabase.rpc("create_workout_version",{p_student_id:studentId,p_name:planForm.name,p_focus:planForm.focus||null,p_review_at:planForm.review_at||null,p_notes:planForm.notes||null});if(error){setMessage(error.message);return;}setPlanOpen(false);setPlanForm(blankPlan);setMessage("Novo plano criado. Adicione exercícios e publique quando estiver pronto.");await loadPlans(studentId);if(data) {const id=typeof data==="string"?data:data.id;const found=(await supabase.from("workout_plans").select("*").eq("id",id).single()).data;if(found){setPlan(found as WorkoutPlan);await loadItems(id);}}}
 async function selectPlan(next:WorkoutPlan){setPlan(next);await loadItems(next.id);}
 async function addExercise(item:ExerciseLibraryItem){if(!plan)return;const position=items.length;const {error}=await supabase.from("workout_exercises").insert({plan_id:plan.id,exercise_id:item.id,name:item.name,muscle_group:item.muscle_group,equipment:item.equipment,media_url:item.media_url,media_type:item.media_type,sets:item.default_sets,reps_min:item.default_reps_min,reps_max:item.default_reps_max,rest_seconds:item.default_rest_seconds,initial_load_kg:0,notes:item.notes,position});if(error){setMessage(error.message);return;}await loadItems(plan.id);}
 async function createAndAddExercise(e:FormEvent){e.preventDefault();if(!profile)return;const {data,error}=await supabase.from("exercise_library").insert({...exerciseForm,created_by:profile.id}).select("*").single();if(error){setMessage(error.message);return;}setExerciseOpen(false);setExerciseForm(blankExercise);await loadLibrary();if(data)await addExercise(data as ExerciseLibraryItem);}
 async function removeExercise(id:string){if(!plan)return;await supabase.from("workout_exercises").delete().eq("id",id);await loadItems(plan.id);}
 async function updateExercise(id:string,key:string,value:any){await supabase.from("workout_exercises").update({[key]:value}).eq("id",id);setItems(current=>current.map(x=>x.id===id?{...x,[key]:value}:x));}
 async function publish(){if(!plan)return;const {error}=await supabase.rpc("activate_workout_plan",{p_plan_id:plan.id});if(error){setMessage(error.message);return;}setMessage("Treino publicado para o aluno.");await loadPlans(studentId);}
 return <StaffShell title="Treinos dos alunos" subtitle="Crie versões, adicione exercícios e publique o plano do aluno." right={<button className="button small primary" onClick={()=>setPlanOpen(true)}><Icon name="plus"/> Criar treino</button>}>
  <div className="staff-toolbar"><label className="field compact"><span>Aluno</span><select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Selecione</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><div className="plan-chips">{plans.map(x=><button key={x.id} className={plan?.id===x.id?"active":""} onClick={()=>void selectPlan(x)}>{x.name} · v{x.version}{x.is_active?" ✓":""}</button>)}</div></div>
  {message&&<div className="notice info"><Icon name="info"/><span>{message}</span></div>}
  {loading?<div className="skeleton hero"/>:!studentId?<EmptyState icon="users" title="Selecione um aluno" text="Escolha um aluno ativo para montar o treino."/>:!plan?<EmptyState icon="dumbbell" title="Aluno sem treino" text="Crie o primeiro plano e adicione exercícios." action={<button className="button primary" onClick={()=>setPlanOpen(true)}><Icon name="plus"/> Criar treino</button>}/>:<>
   <Card className="plan-summary"><div><span className={plan.is_active?"status-pill active":"status-pill pending"}>{plan.is_active?"PUBLICADO":"RASCUNHO"}</span><h2>{plan.name} · versão {plan.version}</h2><p>{plan.focus||"Sem foco definido"}{plan.review_at?` · revisão ${plan.review_at}`:""}</p></div><button className="button primary" onClick={publish} disabled={plan.is_active||items.length===0}><Icon name="check"/> {plan.is_active?"Publicado":"Publicar treino"}</button></Card>
   <div className="workout-builder"><section><div className="section-heading"><h2>Exercícios do treino</h2><span>{items.length} itens</span></div>{items.length===0?<EmptyState icon="plus" title="Adicione o primeiro exercício" text="Use as sugestões ao lado ou crie um exercício novo."/>:<div className="builder-list">{items.map((item,index)=><Card key={item.id}><b>{index+1}</b><div><strong>{item.name}</strong><small>{item.muscle_group} · {item.equipment}</small><div className="inline-inputs"><label>Séries<input type="number" value={item.sets} onChange={e=>void updateExercise(item.id,"sets",Number(e.target.value))}/></label><label>Reps<input value={`${item.reps_min}-${item.reps_max}`} onChange={e=>{const [min,max]=e.target.value.split("-").map(Number);if(min)void updateExercise(item.id,"reps_min",min);if(max)void updateExercise(item.id,"reps_max",max)}}/></label><label>Desc.<input type="number" value={item.rest_seconds} onChange={e=>void updateExercise(item.id,"rest_seconds",Number(e.target.value))}/></label><label>Carga<input type="number" value={item.initial_load_kg} onChange={e=>void updateExercise(item.id,"initial_load_kg",Number(e.target.value))}/></label></div></div><button className="icon-button danger" onClick={()=>void removeExercise(item.id)}><Icon name="trash"/></button></Card>)}</div>}</section>
    <aside><div className="section-heading"><h2>Sugestões</h2><button className="button small outline" onClick={()=>setExerciseOpen(true)}><Icon name="plus"/> Novo</button></div><label className="search-box"><Icon name="search"/><input placeholder="Buscar exercício" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="suggestion-list">{suggestions.map(item=><button key={item.id} onClick={()=>void addExercise(item)}><span><strong>{item.name}</strong><small>{item.muscle_group} · {item.equipment}</small></span><Icon name="plus"/></button>)}</div></aside>
   </div>
  </>}
  <Modal open={planOpen} title="Criar nova versão de treino" onClose={()=>setPlanOpen(false)}><form className="form-grid one-column" onSubmit={createPlan}><InputField label="Nome" value={planForm.name} onChange={e=>setPlanForm({...planForm,name:e.target.value})}/><InputField label="Foco" value={planForm.focus} onChange={e=>setPlanForm({...planForm,focus:e.target.value})}/><InputField label="Data de revisão" type="date" value={planForm.review_at} onChange={e=>setPlanForm({...planForm,review_at:e.target.value})}/><TextareaField label="Observações" value={planForm.notes} onChange={e=>setPlanForm({...planForm,notes:e.target.value})}/><button className="button primary">Criar treino</button></form></Modal>
  <Modal open={exerciseOpen} title="Adicionar exercício novo" onClose={()=>setExerciseOpen(false)} wide><form className="form-grid" onSubmit={createAndAddExercise}><InputField label="Nome" value={exerciseForm.name} onChange={e=>setExerciseForm({...exerciseForm,name:e.target.value})}/><InputField label="Grupo muscular" value={exerciseForm.muscle_group} onChange={e=>setExerciseForm({...exerciseForm,muscle_group:e.target.value})}/><InputField label="Equipamento" value={exerciseForm.equipment} onChange={e=>setExerciseForm({...exerciseForm,equipment:e.target.value})}/><InputField label="URL do GIF, imagem ou vídeo" value={exerciseForm.media_url} onChange={e=>setExerciseForm({...exerciseForm,media_url:e.target.value})}/><InputField label="Séries" type="number" value={exerciseForm.default_sets} onChange={e=>setExerciseForm({...exerciseForm,default_sets:Number(e.target.value)})}/><InputField label="Repetições mínimas" type="number" value={exerciseForm.default_reps_min} onChange={e=>setExerciseForm({...exerciseForm,default_reps_min:Number(e.target.value)})}/><InputField label="Repetições máximas" type="number" value={exerciseForm.default_reps_max} onChange={e=>setExerciseForm({...exerciseForm,default_reps_max:Number(e.target.value)})}/><InputField label="Descanso (s)" type="number" value={exerciseForm.default_rest_seconds} onChange={e=>setExerciseForm({...exerciseForm,default_rest_seconds:Number(e.target.value)})}/><TextareaField label="Orientações" value={exerciseForm.notes} onChange={e=>setExerciseForm({...exerciseForm,notes:e.target.value})}/><button className="button primary span-2">Salvar e adicionar</button></form></Modal>
 </StaffShell>;
}
