import { useEffect, useMemo, useState } from "react";
import AppShell, { Card } from "../components/AppShell";
import EmptyState from "../components/EmptyState";
import Modal from "../components/Modal";
import Icon from "../components/Icon";
import { useAuth } from "../context/AuthContext";
import { supabase } from "../lib/supabase";

interface DietPlan { calories_goal:number; protein_goal:number; carbs_goal:number; fat_goal:number; fiber_goal:number; water_goal_ml:number; notes?:string | null; }
interface NutritionLog { log_date:string; calories:number; protein_g:number; carbs_g:number; fat_g:number; fiber_g:number; water_ml:number; }
interface Food { id:string; name:string; category:string; kcal_per_100g:number; protein_g:number; carbs_g:number; fat_g:number; fiber_g:number; image_url:string | null; }
interface Recipe { id:string; title:string; description:string | null; meal_type:string | null; prep_minutes:number | null; servings:number; calories:number; protein_g:number; carbs_g:number; fat_g:number; fiber_g:number; image_url:string | null; ingredients:unknown; steps:unknown; }

const receptionUrl = "https://wa.me/551147181730?text=Olá,%20gostaria%20de%20liberar%20a%20área%20Minha%20Dieta%20no%20app%20Accqua%20Sports.";

function percent(value:number, goal:number){return Math.max(0,Math.min(100,Math.round((value/Math.max(goal,1))*100)));}
function asList(value:unknown):string[]{if(Array.isArray(value))return value.map(String);if(typeof value==="string")return value.split("\n").filter(Boolean);return [];}

export default function Diet(){
 const {user,profile,dietAccess,refreshDietAccess}=useAuth();
 const [tab,setTab]=useState<"daily"|"weekly"|"monthly">("daily");
 const [plan,setPlan]=useState<DietPlan|null>(null); const [logs,setLogs]=useState<NutritionLog[]>([]);
 const [foods,setFoods]=useState<Food[]>([]); const [recipes,setRecipes]=useState<Recipe[]>([]); const [loading,setLoading]=useState(true);
 const [selected,setSelected]=useState<{type:"food"|"recipe"|"tip";data:any}|null>(null);
 const active = dietAccess?.status === "active" && (!dietAccess.expires_at || new Date(dietAccess.expires_at)>new Date());

 useEffect(()=>{if(!active||!user){setLoading(false);return;}void (async()=>{setLoading(true);await supabase.rpc("ensure_diet_plan");const [planResult,logsResult,foodsResult,recipesResult]=await Promise.all([
  supabase.from("diet_plans").select("*").eq("user_id",user.id).maybeSingle(),
  supabase.from("nutrition_daily_logs").select("*").eq("user_id",user.id).gte("log_date",new Date(Date.now()-35*86400000).toISOString().slice(0,10)).order("log_date"),
  supabase.from("foods").select("*").eq("active",true).order("position").limit(12),
  supabase.from("recipes").select("*").eq("active",true).order("position").limit(10),
 ]);setPlan(planResult.data as DietPlan|null);setLogs((logsResult.data||[]) as NutritionLog[]);setFoods((foodsResult.data||[]) as Food[]);setRecipes((recipesResult.data||[]) as Recipe[]);setLoading(false);})();},[active,user]);

 const todayKey=new Date().toISOString().slice(0,10); const today=logs.find(l=>l.log_date===todayKey)||{log_date:todayKey,calories:0,protein_g:0,carbs_g:0,fat_g:0,fiber_g:0,water_ml:0};
 const relevant=useMemo(()=>tab==="daily"?[today]:tab==="weekly"?logs.slice(-7):logs.slice(-30),[tab,logs,todayKey]);
 const summary=useMemo(()=>{const count=Math.max(relevant.length,1);const total=relevant.reduce((a,l)=>({calories:a.calories+l.calories,protein_g:a.protein_g+l.protein_g,carbs_g:a.carbs_g+l.carbs_g,fat_g:a.fat_g+l.fat_g,fiber_g:a.fiber_g+l.fiber_g,water_ml:a.water_ml+l.water_ml}),{calories:0,protein_g:0,carbs_g:0,fat_g:0,fiber_g:0,water_ml:0});return tab==="daily"?total:{calories:Math.round(total.calories/count),protein_g:Math.round(total.protein_g/count),carbs_g:Math.round(total.carbs_g/count),fat_g:Math.round(total.fat_g/count),fiber_g:Math.round(total.fiber_g/count),water_ml:Math.round(total.water_ml/count)};},[relevant,tab]);

 async function addWater(){if(!user||!plan)return;const next=Math.min(plan.water_goal_ml*2,today.water_ml+300);await supabase.from("nutrition_daily_logs").upsert({user_id:user.id,log_date:todayKey,water_ml:next},{onConflict:"user_id,log_date"});setLogs(current=>{const found=current.some(l=>l.log_date===todayKey);return found?current.map(l=>l.log_date===todayKey?{...l,water_ml:next}:l):[...current,{...today,water_ml:next}];});}

 if(!active)return <AppShell title="Minha dieta" back right={<button className="icon-button"><Icon name="info"/></button>}><div className="diet-locked card"><span><Icon name="apple" size={48}/></span><em>PREMIUM</em><h1>Sua análise nutricional personalizada</h1><p>Esta área usa os dados informados no primeiro acesso para acompanhar metas, hidratação, alimentos e receitas. O acesso é liberado após a contratação.</p><ul><li>Análises diária, semanal e mensal</li><li>Macronutrientes, água e fibras</li><li>Alimentos e receitas recomendadas</li><li>Metas ajustadas pela equipe</li></ul><a className="button primary large" href={import.meta.env.VITE_DIET_CHECKOUT_URL||receptionUrl} target="_blank" rel="noreferrer">Liberar Minha Dieta</a><button className="text-button" onClick={()=>void refreshDietAccess()}>Já paguei — verificar acesso</button></div></AppShell>;
 if(loading||!plan)return <AppShell title="Minha dieta" back><div className="skeleton hero"/><div className="skeleton card-line"/></AppShell>;

 const caloriePct=percent(summary.calories,plan.calories_goal); const waterPct=percent(summary.water_ml,plan.water_goal_ml); const fiberPct=percent(summary.fiber_g,plan.fiber_goal);
 const tips=[{icon:"leaf",title:"Aumente o consumo de fibras",text:summary.fiber_g<plan.fiber_goal?`Faltam em média ${Math.max(0,plan.fiber_goal-summary.fiber_g)} g para sua meta.`:"Sua ingestão de fibras está dentro da meta."},{icon:"water",title:"Hidratação",text:summary.water_ml<plan.water_goal_ml?"Distribua mais água ao longo do dia.":"Meta de água atingida. Muito bem!"},{icon:"star",title:"Equilíbrio nutricional",text:summary.protein_g>=plan.protein_goal*.8?"Seu consumo de proteínas está equilibrado.":"Inclua uma fonte de proteína nas principais refeições."}];
 return <AppShell title="Minha dieta" back right={<button className="icon-button"><Icon name="info"/></button>}>
  <div className="diet-tabs"><button className={tab==="daily"?"active":""} onClick={()=>setTab("daily")}>Diária</button><button className={tab==="weekly"?"active":""} onClick={()=>setTab("weekly")}>Semanal</button><button className={tab==="monthly"?"active":""} onClick={()=>setTab("monthly")}>Mensal</button></div>
  <Card className="calorie-card"><div className="card-heading"><div><Icon name="flame"/><span><strong>{tab==="daily"?"Calorias de hoje":tab==="weekly"?"Média da semana":"Média do mês"}</strong><small>{summary.calories.toLocaleString("pt-BR")} kcal de {plan.calories_goal.toLocaleString("pt-BR")}</small></span></div><b>{caloriePct}%</b></div><div className="nutrition-chart">{(relevant.length?relevant:Array.from({length:7},(_,i)=>({...today,calories:0,log_date:String(i)}))).slice(-7).map((log,i)=><i key={`${log.log_date}-${i}`} style={{height:`${Math.max(8,Math.min(100,(log.calories/Math.max(plan.calories_goal,1))*100))}%`}}><span>{log.calories||""}</span></i>)}</div><div className="progress"><i style={{width:`${caloriePct}%`}}/></div></Card>
  <button className="macro-card card" onClick={()=>setSelected({type:"tip",data:{title:"Distribuição de macronutrientes",text:"Proteínas apoiam recuperação muscular, carboidratos fornecem energia e gorduras participam de funções hormonais. As metas são ajustáveis pela equipe."}})}><div className="macro-donut" style={{"--protein":`${percent(summary.protein_g,Math.max(summary.protein_g+summary.carbs_g+summary.fat_g,1))*3.6}deg`} as any}><strong>{caloriePct}%</strong></div><div className="macro-list"><span><i className="blue"/>Proteínas <b>{summary.protein_g} g</b></span><span><i className="green"/>Carboidratos <b>{summary.carbs_g} g</b></span><span><i className="orange"/>Gorduras <b>{summary.fat_g} g</b></span></div><Icon name="next"/></button>
  <div className="water-fiber-grid"><Card className="water-card"><div><Icon name="water"/><span><strong>Água</strong><small>{(summary.water_ml/1000).toFixed(1)} / {(plan.water_goal_ml/1000).toFixed(1)} L</small></span></div><div className="water-cups">{Array.from({length:Math.max(1,Math.ceil(plan.water_goal_ml/300))},(_,i)=><i key={i} className={i<Math.round(summary.water_ml/300)?"full":""}/>)}</div>{tab==="daily"&&<button onClick={addWater}>+ Registrar copo</button>}<div className="progress blue"><i style={{width:`${waterPct}%`}}/></div></Card><Card><div><Icon name="leaf"/><span><strong>Fibras</strong><small>{summary.fiber_g} / {plan.fiber_goal} g</small></span></div><div className="progress green"><i style={{width:`${fiberPct}%`}}/></div></Card></div>
  <section className="horizontal-section"><div className="section-heading"><h2>Alimentos em destaque</h2><button onClick={()=>setSelected({type:"food",data:foods})}>Ver todos</button></div><div className="horizontal-cards">{foods.slice(0,4).map(food=><button key={food.id} onClick={()=>setSelected({type:"food",data:food})}><img src={food.image_url||"https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=300&q=70"} alt=""/><strong>{food.name}</strong><small>{food.kcal_per_100g} kcal · 100 g</small></button>)}</div></section>
  <section className="suggestions-compact"><h2>Sugestões para você</h2><div>{tips.map(tip=><button key={tip.title} onClick={()=>setSelected({type:"tip",data:tip})}><Icon name={tip.icon}/><span><strong>{tip.title}</strong><small>{tip.text}</small></span><Icon name="next"/></button>)}</div></section>
  <section className="horizontal-section recipes"><div className="section-heading"><h2>Receitas recomendadas</h2><button onClick={()=>setSelected({type:"recipe",data:recipes})}>Ver todas</button></div><div className="horizontal-cards">{recipes.slice(0,3).map(recipe=><button key={recipe.id} onClick={()=>setSelected({type:"recipe",data:recipe})}><img src={recipe.image_url||"https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=400&q=70"} alt=""/><strong>{recipe.title}</strong><small>{recipe.calories} kcal</small></button>)}</div></section>
  <Modal open={Boolean(selected)} title={selected?.type==="recipe"?"Receita":selected?.type==="food"?"Informações do alimento":"Sugestão personalizada"} onClose={()=>setSelected(null)}>
   {selected?.type==="tip"&&<div className="detail-copy"><Icon name={selected.data.icon||"info"} size={42}/><h2>{selected.data.title}</h2><p>{selected.data.text}</p></div>}
   {selected?.type==="food"&&!Array.isArray(selected.data)&&<div className="food-detail"><img src={selected.data.image_url||"https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=500&q=80"}/><h2>{selected.data.name}</h2><div className="detail-stats"><span>{selected.data.kcal_per_100g}<small>kcal</small></span><span>{selected.data.protein_g}g<small>proteínas</small></span><span>{selected.data.carbs_g}g<small>carboidratos</small></span><span>{selected.data.fat_g}g<small>gorduras</small></span></div></div>}
   {selected?.type==="food"&&Array.isArray(selected.data)&&<div className="modal-list">{selected.data.map((f:Food)=><button key={f.id} onClick={()=>setSelected({type:"food",data:f})}><strong>{f.name}</strong><span>{f.kcal_per_100g} kcal / 100 g</span><Icon name="next"/></button>)}</div>}
   {selected?.type==="recipe"&&!Array.isArray(selected.data)&&<div className="recipe-detail"><img src={selected.data.image_url||"https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=600&q=80"}/><h2>{selected.data.title}</h2><p>{selected.data.description}</p><div className="detail-stats"><span>{selected.data.calories}<small>kcal</small></span><span>{selected.data.protein_g}g<small>proteínas</small></span><span>{selected.data.prep_minutes||0}<small>minutos</small></span></div><h3>Ingredientes</h3><ol>{asList(selected.data.ingredients).map((x,i)=><li key={i}>{x}</li>)}</ol><h3>Modo de preparo</h3><ol>{asList(selected.data.steps).map((x,i)=><li key={i}>{x}</li>)}</ol></div>}
   {selected?.type==="recipe"&&Array.isArray(selected.data)&&<div className="modal-list">{selected.data.map((r:Recipe)=><button key={r.id} onClick={()=>setSelected({type:"recipe",data:r})}><strong>{r.title}</strong><span>{r.calories} kcal · {r.prep_minutes||0} min</span><Icon name="next"/></button>)}</div>}
  </Modal>
 </AppShell>;
}
