import "./verify-visual-contracts-1.5.9.mjs";
import fs from "node:fs";import path from "node:path";import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const failures=[];const passes=[];const read=(file)=>fs.readFileSync(path.join(root,file),"utf8");const requireMatch=(id,file,pattern,note)=>pattern.test(read(file))?passes.push(id):failures.push(`${id} — ${note} (${file})`);const requireAll=(id,file,patterns,note)=>patterns.every((p)=>p.test(read(file)))?passes.push(id):failures.push(`${id} — ${note} (${file})`);const requireAbsent=(id,file,pattern,note)=>!pattern.test(read(file))?passes.push(id):failures.push(`${id} — ${note} (${file})`);
const css="scr/styles/build-1.6.0.css";requireMatch("160/version","package.json",/"version":\s*"1\.6\.0"/,"package não está em 1.6.0");requireMatch("160/contracts","package.json",/verify-visual-contracts-1\.6\.0\.mjs/,"npm não executa contratos 1.6.0");requireMatch("160/css-last","scr/main.tsx",/build-1\.5\.9\.css";\s*\nimport "\.\/styles\/build-1\.6\.0\.css";/,"camada 1.6.0 não é a última");
requireAll("160/sidebar-panel","scr/components/StaffLayout.tsx",[/<rect x="3" y="4"/,/M9 4v16/,/usesInternalPageScroll/],"sidebar não usa painel/scroll compartilhado");requireAll("160/shared-layout","scr/components/StaffPageLayout.tsx",[/staff-page-layout/,/staff-page-layout-scroll/],"shell Staff compartilhado ausente");for(const page of ["scr/pages/NotificationsStaff.tsx","scr/pages/RankingStaff.tsx","scr/pages/ClassesAdminV155.tsx"])requireMatch(`160/page-${page}`,page,/StaffPageLayout/,"subpágina não usa shell compartilhado");requireAll("160/classes","scr/pages/ClassesAdmin.tsx",[/expandedId/,/setExpandedId/,/aria-expanded={isOpen}/],"accordion não tem fonte única");requireAbsent("160/no-class-hack","scr/pages/ClassesAdminV155.tsx",/v155ForceCollapsed|document\.addEventListener\("click"/,"hack de collapse ainda existe");
requireAll("160/store","scr/lib/store.ts",[/\.is\("excluido_em",null\)/,/accqua_staff_soft_delete_product_v1_5_5/],"soft-delete não está canônico");requireAll("160/trash","scr/components/swipeable-list-item.css",[/top:-9px/,/right:-9px/,/transform:none/],"lixeira compartilhada cobre conteúdo");requireAll("160/thumbs","scr/components/ExerciseMedia.tsx",[/compactImageCandidate/,/render\/image\/public/,/decoding="async"/],"thumbnail leve não está implementado");
requireAll("160/method-copy",css,[/workout-entry-methods button p/,/opacity:1!important/,/max-height:none!important/],"subtítulos ainda dependem de hover");requireAll("160/progress","scr/pages/AdminWorkoutBuilder.tsx",[/function StepProgress/,/<StepProgress current={mobileStep}/],"progresso único ausente");requireAll("160/progress-css",css,[/admin-builder-progress-v160/,/admin-builder-mobile-progress,[\s\S]*?admin-builder-step-nav[\s\S]*?display:none!important/],"progresso antigo continua visível");requireAll("160/footer","scr/pages/AdminWorkoutBuilder.tsx",[/<\/main>\s*\n\s*<footer className="admin-builder-footer">/,/ETAPA ATUAL/,/Salvar como modelo/],"footer não pertence à viewport");requireAll("160/grid",css,[/minmax\(260px,320px\) minmax\(0,1fr\) minmax\(0,280px\)/,/max-width:1279px/,/admin-builder-compact-tools-trigger/],"grid/drawer 3→2 não está protegido");requireAll("160/carousel",css,[/scroll-snap-type:x mandatory/,/min-width:88px!important/],"divisão não tem snap");requireAll("160/stepper",css,[/admin-builder-quick-tune b/,/white-space:nowrap/],"stepper pode quebrar reps");requireAll("160/methods","scr/pages/AdminWorkoutBuilder.tsx",[/MÉTODOS DE MONTAGEM/,/admin-builder-guide-button is-aside/,/admin-v160-compact-methods/],"métodos continuam dispersos");
requireAll("160/login","scr/pages/Login.tsx",[/concept-login-form[\s\S]*?concept-feedback/,/concept-first-access[\s\S]*?concept-google-link/],"login continua com feedback/Google fora do fluxo");requireAll("160/home",css,[/accqua-menu-header-actions[\s\S]*?min-height:44px/,/accqua-membership-shield,[\s\S]*?width:44px/,/accqua-checkin-button[\s\S]*?height:44px/],"topbar desalinhada");requireAll("160/modal",css,[/responsive-dialog-header{gap:24px/,/accqua-modal-close-button/],"X do modal sem respiro");
if(failures.length){console.error("\nACCQUA Build 1.6.0 — contratos FALHARAM:\n");failures.forEach((f)=>console.error(` - ${f}`));process.exit(1)}console.log(`ACCQUA Build 1.6.0 — ${passes.length} contratos validados.`);
