-- Build 1.6.5.5 — owner-only Staff account security.
-- The owner is resolved by canonical Auth email instead of a generated UUID.

create or replace function public.is_accqua_owner_v1_6_5_5()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from auth.users u
    where u.id = auth.uid()
      and lower(coalesce(u.email, '')) = 'rafaalexandrowitch@professor.com'
  );
$$;

revoke all on function public.is_accqua_owner_v1_6_5_5() from public, anon;
grant execute on function public.is_accqua_owner_v1_6_5_5() to authenticated, service_role;

create or replace function public.accqua_guard_profile_privileges_v1_6_5_5()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  actor_is_service boolean := (
    current_user in ('service_role', 'supabase_admin', 'supabase_auth_admin', 'postgres')
    or coalesce(current_setting('request.jwt.claim.role', true), '') = 'service_role'
  );
  actor_is_owner boolean := public.is_accqua_owner_v1_6_5_5();
  target_is_owner boolean := false;
begin
  if tg_op = 'INSERT' then
    -- A normal authenticated user can only originate as a pending student.
    if new.role <> 'student'::public.app_role and not actor_is_service and not actor_is_owner then
      raise exception 'staff_role_change_forbidden' using errcode = '42501';
    end if;
    return new;
  end if;

  select exists (
    select 1 from auth.users u
    where u.id = old.id
      and lower(coalesce(u.email, '')) = 'rafaalexandrowitch@professor.com'
  ) into target_is_owner;

  if new.role is distinct from old.role and not actor_is_service and not actor_is_owner then
    raise exception 'staff_role_change_forbidden' using errcode = '42501';
  end if;

  -- Nobody in ordinary Staff can demote, block, or relabel the owner account.
  if target_is_owner
     and (
       new.role is distinct from old.role
       or new.status is distinct from old.status
       or new.email is distinct from old.email
     )
     and not actor_is_service
     and not actor_is_owner then
    raise exception 'owner_account_protected' using errcode = '42501';
  end if;

  return new;
end;
$$;

revoke all on function public.accqua_guard_profile_privileges_v1_6_5_5() from public, anon, authenticated;

drop trigger if exists accqua_guard_profile_privileges_v1_6_5_5 on public.profiles;
create trigger accqua_guard_profile_privileges_v1_6_5_5
before insert or update on public.profiles
for each row execute function public.accqua_guard_profile_privileges_v1_6_5_5();

-- Remove the historical permissive INSERT policy that allowed a self-created
-- profile to choose privileged role/status values. Recreate it safely.
drop policy if exists profiles_accqua_self_insert on public.profiles;
drop policy if exists profiles_accqua_self_insert_guarded_v1655 on public.profiles;
create policy profiles_accqua_self_insert_guarded_v1655
on public.profiles
for insert
to authenticated
with check (
  id = auth.uid()
  and role = 'student'::public.app_role
  and status = 'pending'::public.membership_status
);

create table if not exists public.accqua_staff_account_audit (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('create')),
  created_by uuid not null references auth.users(id) on delete restrict,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  target_email text not null,
  target_role public.app_role not null check (target_role <> 'student'::public.app_role),
  created_at timestamptz not null default now()
);

alter table public.accqua_staff_account_audit enable row level security;

drop policy if exists accqua_staff_account_audit_owner_read_v1655 on public.accqua_staff_account_audit;
create policy accqua_staff_account_audit_owner_read_v1655
on public.accqua_staff_account_audit
for select
to authenticated
using (public.is_accqua_owner_v1_6_5_5());

grant select on public.accqua_staff_account_audit to authenticated;
grant insert on public.accqua_staff_account_audit to service_role;
grant usage, select on sequence public.accqua_staff_account_audit_id_seq to service_role;
